# Generated by Django 3.2.14 on 2022-08-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_auto_20220729_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='comment',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
    ]
